app:
  env: dev
  log:
    level: DEBUG

spring:
  mail:
    host: ${RSS_SUBSCRIBER_SMTP_HOST}
    port:
    username: ${RSS_SUBSCRIBER_SMTP_USERNAME}
    password: ${RSS_SUBSCRIBER_SMTP_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.2.229:33061/rsssub?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xiaohao943
    initialization-mode: always

server:
  port: 8888
  forward-headers-strategy: native
  compression:
    enabled: false
  error:
    include-message: always
  servlet:
    encoding:
      charset: UTF-8

logging:
  level:
    cn.liguohao.rss.subscriber: ${app.log.level}
  file:
    name: logs/rss-subscriber-dev.log

